name: Helm

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Chart Checkout
        uses: actions/checkout@v2
      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0
      - name: Helm Repository Checkout
        uses: actions/checkout@v2
        with:
          repository: yourorg/helm-repo
          token: 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
          fetch-depth: 0
          persist-credentials: true
          ref: main
          path: helm
      - name: Helm Package
        run: helm package helm --version "0.1.0+$(git rev-parse --short "$GITHUB_SHA")" -d main
      - name: Helm Push
        env:
          GITHUB_TOKEN: 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
        run: |
          git config --global user.email "shwetaskyadav457@gmail.com"
          git config --global user.name "Shweta-Ydv"
          CHART_PACKAGE_NAME="my-chart-0.1.0+$(git rev-parse --short "$GITHUB_SHA").tgz"
          cd helm-repo
          git add "$CHART_PACKAGE_NAME"
          git commit -m "$CHART_PACKAGE_NAME"
          git push origin main
